[package]
name = "os_window"
version = "0.1.0"
authors = ["Jendrik Illner <jendrik.illner@gmail.com>"]
edition = "2018"

[dependencies]
winapi = { version = "0.3", features = ["winuser"] }

[lib]
crate-type = ["dylib"]
path = "./src/os_window_lib.rs"